[versions]
# Android
compileSdk = "33"
targetSdk = "33"
minSdk = "21"
buildToolVersion = "30.0.3"
kotlin = "1.7.20"
core-ktx = "1.3.2"
appcompat = "1.2.0"
material = "1.2.1"
constraintlayout = "2.0.4"
hilt-work = "1.0.0"
room = "2.5.2"

# Testing
junit = "4.13.1"
androidx-test-ext = "1.1.2"
espresso-core = "3.3.0"

# Libraries
gson = "2.8.6"
jxl = "2.6.12"
hilt = "2.44"
coroutines = "1.6.4"
lifecycle = "2.5.1"
navigation = "2.5.3"
epoxy = "4.6.4"
timber = "4.7.1"

[libraries]
# Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# Libraries
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jxl = { group = "net.sourceforge.jexcelapi", name = "jxl", version.ref = "jxl" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Lifecycle
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

# Navigation
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

# Epoxy
epoxy = { group = "com.airbnb.android", name = "epoxy", version.ref = "epoxy" }
epoxy-processor = { group = "com.airbnb.android", name = "epoxy-processor", version.ref = "epoxy" }

# Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Hilt WorkManager
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }
hilt-work-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-work" }

[plugins]
android-application = { id = "com.android.application", version = "7.4.2" }
android-library = { id = "com.android.library", version = "7.4.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version = "2.5.3" } 